### ISSUE TITLE
Maximum and Sum Intensity Projection Tests

### ISSUE THREAD

**Issue by ian-coccimiglio** [haesleinhuepf/human-eval-bia#116]
Going through the test cases, I noticed something interesting. Both the [maximum_intensity_projection.ipynb](https://github.com/haesleinhuepf/human-eval-bia/blob/main/test_cases/maximum_intensity_projection.ipynb) and the [sum_intensity_projection.ipynb](https://github.com/haesleinhuepf/human-eval-bia/blob/main/test_cases/sum_intensity_projection.ipynb) have the same docstring. If I understand everything correctly, this docstring becomes then becomes the prompt.
```
"""
Performs a maximum intensity projection along the first axis of an image.
"""
```

The task with the correct prompt gets a rating almost ~17 spots higher. What's interesting is that newer models still somehow accomplish the task properly, whereas less sophisticated models fail. Which at least implies that they must be interpreting the function name in order to get the desired output, and that therefore we should be mindful of what each function is named.

I'll fix the docstring for the sum_intensity_projection.ipynb

**Comment by haesleinhuepf** [comment]
Solved in #117
