### ISSUE TITLE
Error: name 'Python' is not defined - in llama models

### ISSUE THREAD

**Issue by ian-coccimiglio** [haesleinhuepf/human-eval-bia#80]
I've been working on automating inspection of model outputs, and I've come across a number of errors. One of them in particular shows up a lot.

![image](https://github.com/user-attachments/assets/84792ad1-6b85-45b5-b266-dbc75b59af92)

"name 'Python' is not defined" is an error which appears in 400/10830 benchmark evaluations, or about 3.7% of total test cases. It only seems to be happening to llama models - and is reported as a "syntax error". This explains many of the llama results shown in Figure 6.

![image](https://github.com/user-attachments/assets/b534ad71-6e8b-4988-aab9-58159ff6c590)

Essentially, what's happening is that the LLM outputs
\```Python
\```
instead of:
\```python
\```

My belief is that in the evaluation pipeline, the capital ```Python ``` gets accidentally parsed, and the model throws out the result. This is what's happening when I'm testing these functions locally.

I'm not familiar with the pipeline, but if we could disregard lines starting with backticks, I think that would lower the error rate on llama models substantially.

**Comment by haesleinhuepf** [comment]
Ok, we could fix this in the `extract_python(response)` function, which dxtracts the code from the LLM response in this notebook: https://github.com/haesleinhuepf/human-eval-bia/blob/main/demo/create_samples.ipynb

**Comment by haesleinhuepf** [comment]
And we could fix the current samples by modifying this notebook: https://github.com/haesleinhuepf/human-eval-bia/blob/main/demo/retrieve_code_from_response.ipynb

Afterwards, the code execution/evaluation/plotting  notebooks must be run too.

**Comment by ian-coccimiglio** [comment]
> And we could fix the current samples by modifying this notebook: https://github.com/haesleinhuepf/human-eval-bia/blob/main/demo/retrieve_code_from_response.ipynb
> 
> Afterwards, the code execution/evaluation/plotting notebooks must be run too.

Updates:

- [x] Modified "extract_python" function from create_samples.ipynb in #81.
- [x] Added and enabled "extract_python2" function from retrieve_code_from_responses.ipynb in #81
- [ ] run code execution/evaluation/plotting
