### ISSUE TITLE
Curiosity: If test fails, add to prompt the error description?

### ISSUE THREAD

**Issue by ClementCaporal** [haesleinhuepf/human-eval-bia#97]
Hello,

Maybe it is already describe somewhere in issues but I didn't find it.

I was curious about the benchmark results evolution when you allow a second prompt attempt with the error result.
Will some LLMs be able to correct once they are given one of the assertion of the test case? This might articulate also with #79 

Parallel to this: With an "infinite" number of trial of error is it possible to obtain a perfect score?

Thank you,

Clément

**Comment by haesleinhuepf** [comment]
Hi @ClementCaporal ,

we haven't tested this and it's certainly out of scope for this relatively simple benchmark. I recommend reading [this paper](https://arxiv.org/abs/2303.11366), about "Reflexion", a feedback meachanism: The authors feed results from (failing) unit-tests back to the LLM and allow it to improve the code. They measured: "... Reflexion achieves a 91% pass@1 accuracy on the HumanEval coding benchmark, surpassing the previous state-of-the-art GPT-4 that achieves 80%."

**Comment by ClementCaporal** [comment]
Ok thanks!
